# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lostfounditem',
            index=models.Index(fields=['status', 'is_active'], name='lost_found__status_0f11ea_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfounditem',
            index=models.Index(fields=['category', 'status'], name='lost_found__categor_aab560_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfounditem',
            index=models.Index(fields=['-created_at'], name='lost_found__created_b04f14_idx'),
        ),
        migrations.AddIndex(
            model_name='lostfounditem',
            index=models.Index(fields=['posted_by', 'status'], name='lost_found__posted__115bb7_idx'),
        ),
    ]
