# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancehistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancehistory',
            new_name='attendance__student_74b7bb_idx',
            old_name='att_hist_student_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancehistory',
            new_name='attendance__subject_5f6e3e_idx',
            old_name='att_hist_subject_date_idx',
        ),
        migrations.RenameIndex(
            model_name='subjectattendance',
            new_name='subject_att_student_e438dd_idx',
            old_name='attendance_student_sem_idx',
        ),
        migrations.RenameIndex(
            model_name='subjectattendance',
            new_name='subject_att_student_461537_idx',
            old_name='attendance_student_subject_idx',
        ),
        migrations.AlterField(
            model_name='subjectattendance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
