"""Initial migration for communication app."""
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("channel_type", models.CharField(choices=[("academic_section", "Academic Section"), ("subject", "Subject"), ("coding_community", "Coding Community"), ("placement", "Placement"), ("study_group", "Study Group"), ("faculty", "Faculty"), ("admin_broadcast", "Admin Broadcast"), ("general", "General"), ("club", "Club")], max_length=20)),
                ("visibility", models.CharField(choices=[("public", "Public"), ("private", "Private"), ("restricted", "Restricted")], default="public", max_length=12)),
                ("icon", models.CharField(blank=True, default="💬", max_length=10)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("branch", models.CharField(blank=True, default="", max_length=100)),
                ("semester", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("section", models.CharField(blank=True, default="", max_length=10)),
                ("subject_name", models.CharField(blank=True, default="", max_length=100)),
                ("is_read_only", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("allow_threads", models.BooleanField(default=True)),
                ("allow_reactions", models.BooleanField(default=True)),
                ("allow_file_uploads", models.BooleanField(default=True)),
                ("max_members", models.PositiveIntegerField(default=500)),
                ("slow_mode_seconds", models.PositiveIntegerField(default=0)),
                ("profanity_filter", models.BooleanField(default=True)),
                ("auto_moderation", models.BooleanField(default=True)),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("pinned_message_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_channels", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "comm_channels", "ordering": ["-last_message_at", "name"]},
        ),
        migrations.CreateModel(
            name="DirectConversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_group", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_preview", models.CharField(blank=True, default="", max_length=200)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "comm_direct_conversations", "ordering": ["-last_message_at"]},
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("message_type", models.CharField(choices=[("text", "Text"), ("file", "File"), ("image", "Image"), ("code", "Code Snippet"), ("system", "System"), ("reply", "Reply")], default="text", max_length=10)),
                ("code_language", models.CharField(blank=True, default="", max_length=30)),
                ("attachment", models.FileField(blank=True, null=True, upload_to="chat_attachments/")),
                ("attachment_name", models.CharField(blank=True, default="", max_length=255)),
                ("attachment_size", models.PositiveIntegerField(default=0)),
                ("attachment_mime", models.CharField(blank=True, default="", max_length=100)),
                ("thread_reply_count", models.PositiveIntegerField(default=0)),
                ("mentions", models.JSONField(blank=True, default=list)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_count", models.PositiveIntegerField(default=0)),
                ("read_count", models.PositiveIntegerField(default=0)),
                ("reaction_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="communication.channel")),
                ("conversation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="communication.directconversation")),
                ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sent_messages", to=settings.AUTH_USER_MODEL)),
                ("thread_parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="thread_replies", to="communication.message")),
                ("reply_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="replies", to="communication.message")),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "comm_messages", "ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="ChannelMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("owner", "Owner"), ("admin", "Admin"), ("moderator", "Moderator"), ("member", "Member")], default="member", max_length=12)),
                ("is_muted", models.BooleanField(default=False)),
                ("muted_until", models.DateTimeField(blank=True, null=True)),
                ("is_banned", models.BooleanField(default=False)),
                ("banned_reason", models.TextField(blank=True, default="")),
                ("notification_preference", models.CharField(choices=[("all", "All"), ("mentions", "Mentions Only"), ("none", "None")], default="all", max_length=10)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="communication.channel")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="channel_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "comm_channel_memberships", "unique_together": {("channel", "user")}},
        ),
        migrations.CreateModel(
            name="ConversationParticipant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_muted", models.BooleanField(default=False)),
                ("is_blocked", models.BooleanField(default=False)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="communication.directconversation")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dm_participations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "comm_conversation_participants", "unique_together": {("conversation", "user")}},
        ),
        migrations.CreateModel(
            name="MessageReaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("emoji", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reactions", to="communication.message")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="message_reactions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "comm_message_reactions", "unique_together": {("message", "user", "emoji")}},
        ),
        migrations.CreateModel(
            name="MessageReadReceipt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="read_receipts", to="communication.message")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="message_read_receipts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "comm_message_read_receipts", "unique_together": {("message", "user")}},
        ),
        migrations.CreateModel(
            name="UserPresence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("online", "Online"), ("away", "Away"), ("busy", "Busy"), ("offline", "Offline")], default="offline", max_length=10)),
                ("custom_status", models.CharField(blank=True, default="", max_length=100)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("is_typing_in", models.UUIDField(blank=True, null=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="presence", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "comm_user_presence"},
        ),
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("blocker", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blocked_users", to=settings.AUTH_USER_MODEL)),
                ("blocked", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blocked_by", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "comm_blocked_users", "unique_together": {("blocker", "blocked")}},
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("mute", "Mute User"), ("unmute", "Unmute User"), ("ban", "Ban User"), ("unban", "Unban User"), ("delete_message", "Delete Message"), ("pin_message", "Pin Message"), ("unpin_message", "Unpin Message"), ("lock_channel", "Lock Channel"), ("unlock_channel", "Unlock Channel"), ("archive_channel", "Archive Channel"), ("warn", "Warn User"), ("remove_file", "Remove File")], max_length=20)),
                ("reason", models.TextField(blank=True, default="")),
                ("duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("moderator", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="moderation_actions", to=settings.AUTH_USER_MODEL)),
                ("channel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="moderation_actions", to="communication.channel")),
                ("target_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="moderation_received", to=settings.AUTH_USER_MODEL)),
                ("target_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="communication.message")),
            ],
            options={"db_table": "comm_moderation_actions", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="MessageReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reason", models.CharField(choices=[("spam", "Spam"), ("harassment", "Harassment"), ("inappropriate", "Inappropriate Content"), ("hate_speech", "Hate Speech"), ("misinformation", "Misinformation"), ("other", "Other")], max_length=20)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("reviewed", "Reviewed"), ("resolved", "Resolved"), ("dismissed", "Dismissed")], default="pending", max_length=10)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reporter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="message_reports", to=settings.AUTH_USER_MODEL)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="communication.message")),
                ("channel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="communication.channel")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_reports", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "comm_message_reports", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="TypingIndicator",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("channel", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="communication.channel")),
                ("conversation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="communication.directconversation")),
            ],
            options={"db_table": "comm_typing_indicators"},
        ),
    ]
