# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_channelrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channelrequest',
            new_name='comm_channe_status_5fbc01_idx',
            old_name='comm_chreq_status_idx',
        ),
        migrations.RenameIndex(
            model_name='channelrequest',
            new_name='comm_channe_request_37394b_idx',
            old_name='comm_chreq_user_idx',
        ),
        migrations.AlterField(
            model_name='channelrequest',
            name='purpose',
            field=models.TextField(blank=True, default='', help_text='Why this channel should exist'),
        ),
        migrations.AlterField(
            model_name='channelrequest',
            name='rules',
            field=models.TextField(blank=True, default='', help_text='Proposed channel rules'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['channel_type', 'is_active'], name='comm_channe_channel_656950_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['visibility', 'is_active'], name='comm_channe_visibil_73aead_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['branch', 'semester', 'section'], name='comm_channe_branch_d887f8_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['-last_message_at'], name='comm_channe_last_me_1e6429_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['slug'], name='comm_channe_slug_207e42_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['channel', 'is_banned'], name='comm_channe_channel_410def_idx'),
        ),
        migrations.AddIndex(
            model_name='channelmembership',
            index=models.Index(fields=['user', 'is_banned'], name='comm_channe_user_id_517b13_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='comm_conver_user_id_74fd58_idx'),
        ),
        migrations.AddIndex(
            model_name='directconversation',
            index=models.Index(fields=['-last_message_at'], name='comm_direct_last_me_b38cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', 'created_at'], name='comm_messag_channel_51eb31_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='comm_messag_convers_472f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='comm_messag_sender__ed8fad_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', 'is_pinned'], name='comm_messag_channel_319457_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread_parent', 'created_at'], name='comm_messag_thread__db7082_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='comm_messag_created_117423_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'emoji'], name='comm_messag_message_6220f9_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['status', '-created_at'], name='comm_messag_status_b44610_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['channel', 'status'], name='comm_messag_channel_77fea9_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['channel', '-created_at'], name='comm_modera_channel_05b7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['target_user', '-created_at'], name='comm_modera_target__0f8f20_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action'], name='comm_modera_action_462b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['channel', 'user'], name='comm_typing_channel_ad9e45_idx'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['conversation', 'user'], name='comm_typing_convers_7bb97e_idx'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['status'], name='comm_user_p_status_61a098_idx'),
        ),
        migrations.AddIndex(
            model_name='userpresence',
            index=models.Index(fields=['-last_seen'], name='comm_user_p_last_se_64c0fa_idx'),
        ),
    ]
