# Generated by Django 4.2.13 on 2026-05-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_adminalert_notification_priority_schedulednotification_updates'),
        ('notifications', '0003_extend_notification_types'),
    ]

    operations = [
    ]
