# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_merge_20260525_1713'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminalert',
            new_name='admin_alert_is_read_5f87d0_idx',
            old_name='admin_alerts_unread_idx',
        ),
        migrations.RenameIndex(
            model_name='adminalert',
            new_name='admin_alert_alert_t_57f274_idx',
            old_name='admin_alerts_type_idx',
        ),
        migrations.RenameIndex(
            model_name='adminalert',
            new_name='admin_alert_categor_9483b4_idx',
            old_name='admin_alerts_category_idx',
        ),
        migrations.RenameIndex(
            model_name='adminalert',
            new_name='admin_alert_created_3511c8_idx',
            old_name='admin_alerts_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_a4dd5c_idx',
            old_name='notif_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_611c58_idx',
            old_name='notif_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_notific_19df93_idx',
            old_name='notifications_type_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_priorit_17ee5f_idx',
            old_name='notifications_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulednotification',
            new_name='scheduled_n_status_d18843_idx',
            old_name='scheduled_notifications_status_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulednotification',
            new_name='scheduled_n_target__a582a1_idx',
            old_name='scheduled_notifications_target_idx',
        ),
        migrations.AlterField(
            model_name='schedulednotification',
            name='notification_type',
            field=models.CharField(choices=[('new_resource', 'New Resource'), ('campus_news', 'Campus News'), ('coding_reminder', 'Coding Reminder'), ('system', 'System'), ('academic', 'Academic'), ('placement', 'Placement'), ('event', 'Event'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('attendance', 'Attendance'), ('study_group', 'Study Group'), ('coding_contest', 'Coding Contest'), ('maintenance', 'Maintenance')], default='system', max_length=20),
        ),
    ]
