# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_enhancement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='student_pro_coding__cadff6_idx',
            old_name='profiles_coding_rank_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('resource_view', 'Resource Viewed'), ('resource_download', 'Resource Downloaded'), ('question_solved', 'Question Solved'), ('question_saved', 'Question Saved'), ('news_view', 'News Viewed'), ('profile_update', 'Profile Updated'), ('assignment_submit', 'Assignment Submitted'), ('contest_join', 'Contest Joined'), ('roadmap_progress', 'Roadmap Progress'), ('resume_export', 'Resume Exported')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['activity_type'], name='activity_lo_activit_fd7ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['user'], name='student_pro_user_id_f42457_idx'),
        ),
    ]
