"""Initial migration for events app."""
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, default="", max_length=500)),
                ("event_type", models.CharField(choices=[("hackathon", "Hackathon"), ("coding_contest", "Coding Contest"), ("workshop", "Workshop"), ("seminar", "Seminar"), ("webinar", "Webinar"), ("placement_drive", "Placement Drive"), ("club_event", "Club Event"), ("fest", "Fest"), ("guest_lecture", "Guest Lecture"), ("alumni_session", "Alumni Session"), ("sports", "Sports"), ("cultural", "Cultural"), ("other", "Other")], max_length=20)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("registration_open", "Registration Open"), ("registration_closed", "Registration Closed"), ("ongoing", "Ongoing"), ("completed", "Completed"), ("cancelled", "Cancelled"), ("postponed", "Postponed")], default="draft", max_length=25)),
                ("visibility", models.CharField(choices=[("public", "Public"), ("branch_specific", "Branch Specific"), ("invite_only", "Invite Only")], default="public", max_length=20)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, default="", max_length=255)),
                ("venue_address", models.TextField(blank=True, default="")),
                ("is_online", models.BooleanField(default=False)),
                ("meeting_link", models.URLField(blank=True, default="")),
                ("map_link", models.URLField(blank=True, default="")),
                ("banner_image", models.ImageField(blank=True, null=True, upload_to="events/banners/")),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="events/thumbnails/")),
                ("max_registrations", models.PositiveIntegerField(default=100)),
                ("current_registrations", models.PositiveIntegerField(default=0)),
                ("waitlist_enabled", models.BooleanField(default=True)),
                ("waitlist_count", models.PositiveIntegerField(default=0)),
                ("target_branch", models.CharField(blank=True, default="", max_length=100)),
                ("target_semester", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("target_section", models.CharField(blank=True, default="", max_length=10)),
                ("organizer_name", models.CharField(blank=True, default="", max_length=255)),
                ("organizer_contact", models.CharField(blank=True, default="", max_length=100)),
                ("department", models.CharField(blank=True, default="", max_length=100)),
                ("club_name", models.CharField(blank=True, default="", max_length=100)),
                ("has_certificates", models.BooleanField(default=False)),
                ("has_qr_checkin", models.BooleanField(default=True)),
                ("has_live_chat", models.BooleanField(default=True)),
                ("has_polls", models.BooleanField(default=False)),
                ("has_qa", models.BooleanField(default=False)),
                ("has_feedback", models.BooleanField(default=True)),
                ("materials", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("speakers", models.JSONField(blank=True, default=list)),
                ("agenda", models.JSONField(blank=True, default=list)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("average_rating", models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ("feedback_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organized_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="organized_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "events", "ordering": ["-starts_at"]},
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("registered", "Registered"), ("waitlisted", "Waitlisted"), ("confirmed", "Confirmed"), ("checked_in", "Checked In"), ("attended", "Attended"), ("no_show", "No Show"), ("cancelled", "Cancelled")], default="registered", max_length=15)),
                ("qr_code", models.ImageField(blank=True, null=True, upload_to="events/qr_codes/")),
                ("ticket_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("waitlist_position", models.PositiveIntegerField(blank=True, null=True)),
                ("registration_answers", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="registrations", to="events.event")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_registrations", to=settings.AUTH_USER_MODEL)),
                ("checked_in_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="checkins_performed", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "event_registrations", "ordering": ["-registered_at"], "unique_together": {("event", "user")}},
        ),
        migrations.CreateModel(
            name="EventFeedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rating", models.PositiveSmallIntegerField()),
                ("content_rating", models.PositiveSmallIntegerField(default=3)),
                ("organization_rating", models.PositiveSmallIntegerField(default=3)),
                ("speaker_rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, default="")),
                ("suggestions", models.TextField(blank=True, default="")),
                ("would_recommend", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feedbacks", to="events.event")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_feedbacks", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "event_feedbacks", "ordering": ["-created_at"], "unique_together": {("event", "user")}},
        ),
        migrations.CreateModel(
            name="EventCertificate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("certificate_type", models.CharField(choices=[("participation", "Participation"), ("completion", "Completion"), ("winner", "Winner"), ("runner_up", "Runner Up"), ("speaker", "Speaker"), ("organizer", "Organizer"), ("volunteer", "Volunteer")], default="participation", max_length=15)),
                ("certificate_id", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="events/certificates/")),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="certificates", to="events.event")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_certificates", to=settings.AUTH_USER_MODEL)),
                ("issued_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="issued_certificates", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "event_certificates", "ordering": ["-issued_at"], "unique_together": {("event", "user", "certificate_type")}},
        ),
        migrations.CreateModel(
            name="EventPoll",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=500)),
                ("options", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("allow_multiple", models.BooleanField(default=False)),
                ("total_votes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="polls", to="events.event")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "event_polls", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="EventPollVote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("option_index", models.PositiveSmallIntegerField()),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                ("poll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="events.eventpoll")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "event_poll_votes", "unique_together": {("poll", "user", "option_index")}},
        ),
        migrations.CreateModel(
            name="EventQuestion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("is_answered", models.BooleanField(default=False)),
                ("answer", models.TextField(blank=True, default="")),
                ("upvotes", models.PositiveIntegerField(default=0)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="events.event")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_questions", to=settings.AUTH_USER_MODEL)),
                ("answered_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="answered_event_questions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "event_questions", "ordering": ["-upvotes", "-created_at"]},
        ),
        migrations.CreateModel(
            name="EventQuestionUpvote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="upvote_records", to="events.eventquestion")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "event_question_upvotes", "unique_together": {("question", "user")}},
        ),
        migrations.CreateModel(
            name="EventAnnouncement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="announcements", to="events.event")),
                ("author", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "event_announcements", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="EventChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_messages", to="events.event")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="event_chat_messages", to=settings.AUTH_USER_MODEL)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deleted_event_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "event_chat_messages", "ordering": ["created_at"]},
        ),
    ]
