# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='agenda',
            field=models.JSONField(blank=True, default=list, help_text='Event agenda/schedule'),
        ),
        migrations.AlterField(
            model_name='event',
            name='materials',
            field=models.JSONField(blank=True, default=list, help_text='Event materials/attachments'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.JSONField(blank=True, default=list, help_text='Speaker details'),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='1-5 stars'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'status'], name='events_event_t_e1f6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', '-starts_at'], name='events_status_3c2568_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured', '-starts_at'], name='events_is_feat_09f063_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organized_by', '-starts_at'], name='events_organiz_1ec0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['target_branch', 'target_semester'], name='events_target__ce233a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-starts_at'], name='events_starts__72df37_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_slug_930801_idx'),
        ),
        migrations.AddIndex(
            model_name='eventannouncement',
            index=models.Index(fields=['event', '-created_at'], name='event_annou_event_i_f31178_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcertificate',
            index=models.Index(fields=['user', '-issued_at'], name='event_certi_user_id_86ef0f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcertificate',
            index=models.Index(fields=['certificate_id'], name='event_certi_certifi_28eafa_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcertificate',
            index=models.Index(fields=['event', 'certificate_type'], name='event_certi_event_i_0be494_idx'),
        ),
        migrations.AddIndex(
            model_name='eventchatmessage',
            index=models.Index(fields=['event', 'created_at'], name='event_chat__event_i_c5c799_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfeedback',
            index=models.Index(fields=['event', '-created_at'], name='event_feedb_event_i_b868d2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventpoll',
            index=models.Index(fields=['event', 'is_active'], name='event_polls_event_i_dbe735_idx'),
        ),
        migrations.AddIndex(
            model_name='eventquestion',
            index=models.Index(fields=['event', '-upvotes'], name='event_quest_event_i_e0c845_idx'),
        ),
        migrations.AddIndex(
            model_name='eventquestion',
            index=models.Index(fields=['event', 'is_answered'], name='event_quest_event_i_f5edbc_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='event_regis_event_i_a22351_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['user', 'status'], name='event_regis_user_id_d6b1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['ticket_id'], name='event_regis_ticket__8625a4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', '-registered_at'], name='event_regis_event_i_0710f9_idx'),
        ),
    ]
