# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_useractivitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_admin_i_cd1cac_idx',
            old_name='audit_admin_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_31f574_idx',
            old_name='audit_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_created_43fcd6_idx',
            old_name='audit_created_idx',
        ),
        migrations.RenameIndex(
            model_name='executionlog',
            new_name='execution_l_created_98f4cc_idx',
            old_name='execlog_created_idx',
        ),
        migrations.RenameIndex(
            model_name='executionlog',
            new_name='execution_l_status_d8a5a0_idx',
            old_name='execlog_status_idx',
        ),
        migrations.RenameIndex(
            model_name='executionlog',
            new_name='execution_l_user_id_57ea0f_idx',
            old_name='execlog_user_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='user_activi_user_id_543519_idx',
            old_name='ual_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='user_activi_action_5db802_idx',
            old_name='ual_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='user_activi_ip_addr_dc5c2b_idx',
            old_name='ual_ip_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='user_activi_status_7df15b_idx',
            old_name='ual_status_idx',
        ),
    ]
