# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_contests'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='codingcategory',
            new_name='coding_cate_categor_f2f58a_idx',
            old_name='cat_type_idx',
        ),
        migrations.RenameIndex(
            model_name='codingcategory',
            new_name='coding_cate_is_acti_0825b3_idx',
            old_name='cat_active_idx',
        ),
        migrations.RenameIndex(
            model_name='codingdiscussionmessage',
            new_name='coding_disc_questio_3e6622_idx',
            old_name='coding_discuss_question_created_idx',
        ),
        migrations.RenameIndex(
            model_name='codingdiscussionmessage',
            new_name='coding_disc_user_id_ccd581_idx',
            old_name='coding_discuss_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='codingdraft',
            new_name='coding_draf_user_id_2af3be_idx',
            old_name='coding_drafts_user_question_idx',
        ),
        migrations.RenameIndex(
            model_name='codingdraft',
            new_name='coding_draf_updated_3a7863_idx',
            old_name='coding_drafts_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='codingquestion',
            new_name='coding_ques_topic_5fe04f_idx',
            old_name='coding_topic_diff_idx',
        ),
        migrations.RenameIndex(
            model_name='codingquestion',
            new_name='coding_ques_is_acti_b49855_idx',
            old_name='coding_active_idx',
        ),
        migrations.RenameIndex(
            model_name='contest',
            new_name='coding_cont_status_85d681_idx',
            old_name='coding_contests_status_start_idx',
        ),
        migrations.RenameIndex(
            model_name='contest',
            new_name='coding_cont_starts__124e0d_idx',
            old_name='coding_contests_window_idx',
        ),
        migrations.RenameIndex(
            model_name='contestproblem',
            new_name='coding_cont_contest_9afffd_idx',
            old_name='coding_contest_problem_order_idx',
        ),
        migrations.RenameIndex(
            model_name='contestregistration',
            new_name='coding_cont_contest_8bdbeb_idx',
            old_name='coding_contest_registration_idx',
        ),
        migrations.RenameIndex(
            model_name='contestsubmission',
            new_name='coding_cont_contest_871199_idx',
            old_name='coding_contest_submission_user_idx',
        ),
        migrations.RenameIndex(
            model_name='contestsubmission',
            new_name='coding_cont_contest_28f28b_idx',
            old_name='coding_contest_problem_user_idx',
        ),
        migrations.RenameIndex(
            model_name='contestsubmission',
            new_name='coding_cont_score_905e2f_idx',
            old_name='coding_contest_score_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_user_id_50aaa6_idx',
            old_name='sub_user_question_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_user_id_9864cd_idx',
            old_name='sub_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_questio_6f2493_idx',
            old_name='sub_question_status_idx',
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='starter_code',
            field=models.JSONField(default=dict, help_text='{"python": "...", "java": "...", "cpp": "...", "javascript": "..."}'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='supported_languages',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["python", "java", "cpp", "javascript", "c", "sql"]'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript'), ('c', 'C'), ('sql', 'SQL'), ('go', 'Go')], max_length=15),
        ),
    ]
