# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='criteria',
            field=models.JSONField(default=dict, help_text='Conditions to earn this badge'),
        ),
        migrations.AddIndex(
            model_name='studentxp',
            index=models.Index(fields=['-total_xp'], name='student_xp_total_x_7b24cd_idx'),
        ),
        migrations.AddIndex(
            model_name='studentxp',
            index=models.Index(fields=['rank'], name='student_xp_rank_dd7387_idx'),
        ),
        migrations.AddIndex(
            model_name='studentxp',
            index=models.Index(fields=['level'], name='student_xp_level_b95139_idx'),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['student', '-created_at'], name='xp_transact_student_42866b_idx'),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['source'], name='xp_transact_source_0539d3_idx'),
        ),
    ]
