# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_placement_tracker_upgrade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='placementapplication',
            new_name='placement_a_student_d28f2b_idx',
            old_name='placement_a_student_status_idx',
        ),
        migrations.RenameIndex(
            model_name='placementapplication',
            new_name='placement_a_student_507fba_idx',
            old_name='placement_a_student_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='placementapplication',
            new_name='placement_a_status_352f65_idx',
            old_name='placement_a_status_idx',
        ),
        migrations.AlterField(
            model_name='companynote',
            name='saved_questions',
            field=models.JSONField(blank=True, default=list, help_text='Saved interview questions'),
        ),
        migrations.AlterField(
            model_name='interviewexperience',
            name='experience_notes',
            field=models.TextField(blank=True, default='', help_text='Your experience and tips'),
        ),
        migrations.AlterField(
            model_name='interviewexperience',
            name='questions_asked',
            field=models.TextField(blank=True, default='', help_text='Questions asked during the interview'),
        ),
        migrations.AddIndex(
            model_name='interviewexperience',
            index=models.Index(fields=['application', 'round_number'], name='interview_e_applica_f9e8c3_idx'),
        ),
    ]
