# Generated by Django 4.2.13 on 2026-05-28 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=10)),
                ('related_content_type', models.CharField(blank=True, default='', max_length=50)),
                ('related_content_id', models.UUIDField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_warnings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_warnin_user_id_cd5bec_idx'), models.Index(fields=['issued_by', '-created_at'], name='user_warnin_issued__3b4212_idx'), models.Index(fields=['severity'], name='user_warnin_severit_43cd5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ban_type', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], default='temporary', max_length=10)),
                ('scope', models.CharField(choices=[('platform', 'Platform-wide'), ('chat', 'Chat Only'), ('channel', 'Specific Channel'), ('posting', 'Posting Only')], default='platform', max_length=10)),
                ('reason', models.TextField()),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('lift_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_issued', to=settings.AUTH_USER_MODEL)),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bans_lifted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_bans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_bans_user_id_0ec7f3_idx'), models.Index(fields=['is_active', '-created_at'], name='user_bans_is_acti_c4a9fe_idx'), models.Index(fields=['scope', 'is_active'], name='user_bans_scope_5f467a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModeratorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('global', 'Global Moderator'), ('department', 'Department Moderator'), ('section', 'Section Moderator')], default='global', max_length=15)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('section', models.CharField(blank=True, default='', max_length=10)),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('can_moderate_channels', models.BooleanField(default=True)),
                ('can_moderate_notes', models.BooleanField(default=True)),
                ('can_moderate_roadmaps', models.BooleanField(default=True)),
                ('can_moderate_groups', models.BooleanField(default=True)),
                ('can_moderate_chat', models.BooleanField(default=True)),
                ('can_ban_users', models.BooleanField(default=False)),
                ('can_delete_content', models.BooleanField(default=True)),
                ('can_view_audit_logs', models.BooleanField(default=True)),
                ('total_actions', models.PositiveIntegerField(default=0)),
                ('total_approvals', models.PositiveIntegerField(default=0)),
                ('total_rejections', models.PositiveIntegerField(default=0)),
                ('total_warnings_issued', models.PositiveIntegerField(default=0)),
                ('total_bans_issued', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('appointed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderator_profiles',
                'indexes': [models.Index(fields=['scope', 'is_active'], name='moderator_p_scope_5303e1_idx'), models.Index(fields=['department'], name='moderator_p_departm_d95ac9_idx'), models.Index(fields=['user'], name='moderator_p_user_id_a89d18_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('channel_approved', 'Channel Approved'), ('channel_rejected', 'Channel Rejected'), ('channel_archived', 'Channel Archived'), ('channel_locked', 'Channel Locked'), ('channel_unlocked', 'Channel Unlocked'), ('channel_deleted', 'Channel Deleted'), ('user_warned', 'User Warned'), ('user_muted', 'User Muted'), ('user_unmuted', 'User Unmuted'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('message_deleted', 'Message Deleted'), ('note_approved', 'Note Approved'), ('note_rejected', 'Note Rejected'), ('note_flagged', 'Note Flagged'), ('note_deleted', 'Note Deleted'), ('roadmap_approved', 'Roadmap Approved'), ('roadmap_rejected', 'Roadmap Rejected'), ('roadmap_changes_requested', 'Roadmap Changes Requested'), ('group_suspended', 'Study Group Suspended'), ('group_removed', 'Study Group Removed'), ('content_removed', 'Content Removed'), ('report_resolved', 'Report Resolved'), ('report_rejected', 'Report Rejected'), ('report_escalated', 'Report Escalated')], max_length=30)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_action_logs', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_action_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['moderator', '-created_at'], name='moderation__moderat_1c170c_idx'), models.Index(fields=['action', '-created_at'], name='moderation__action_cf5cc1_idx'), models.Index(fields=['target_user', '-created_at'], name='moderation__target__73d88d_idx'), models.Index(fields=['-created_at'], name='moderation__created_728b69_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('message', 'Chat Message'), ('note', 'Note'), ('roadmap', 'Roadmap'), ('study_group', 'Study Group'), ('profile', 'User Profile'), ('comment', 'Comment'), ('resource', 'Resource'), ('event', 'Event')], max_length=15)),
                ('content_id', models.UUIDField(help_text='ID of the reported content')),
                ('content_preview', models.TextField(blank=True, default='', help_text='Snapshot of reported content')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('hate_speech', 'Hate Speech'), ('copyright', 'Copyright Violation'), ('misinformation', 'Misinformation'), ('impersonation', 'Impersonation'), ('violence', 'Violence/Threats'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('action_taken', models.CharField(blank=True, default='', max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority', '-created_at'], name='content_rep_status_8a6410_idx'), models.Index(fields=['content_type', 'status'], name='content_rep_content_d4c5b6_idx'), models.Index(fields=['reported_user', '-created_at'], name='content_rep_reporte_c8a11a_idx'), models.Index(fields=['assigned_to', 'status'], name='content_rep_assigne_f00822_idx'), models.Index(fields=['-created_at'], name='content_rep_created_40cd26_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('channel', 'Channel Creation'), ('roadmap', 'Roadmap Publication'), ('note', 'Note Publication'), ('study_group', 'Study Group Creation'), ('event', 'Event Publication')], max_length=15)),
                ('content_id', models.UUIDField(help_text='ID of the content awaiting approval')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs Changes')], default='pending', max_length=15)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_type', 'status', '-created_at'], name='approval_re_request_15fdef_idx'), models.Index(fields=['requested_by', 'status'], name='approval_re_request_5440d5_idx'), models.Index(fields=['status', '-created_at'], name='approval_re_status_828555_idx')],
            },
        ),
    ]
