# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cgpa', '0004_gradecomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('cgpa', 'Target CGPA'), ('sgpa', 'Target SGPA'), ('credits', 'Target Credits')], default='cgpa', max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'academic_targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='academicprofile',
            new_name='academic_pr_current_b96d17_idx',
            old_name='cgpa_profile_cgpa_idx',
        ),
        migrations.RenameIndex(
            model_name='academicprofile',
            new_name='academic_pr_academi_5d2046_idx',
            old_name='cgpa_profile_standing_idx',
        ),
        migrations.RenameIndex(
            model_name='cgpahistory',
            new_name='cgpa_histor_user_id_3ffe60_idx',
            old_name='cgpa_history_user_idx',
        ),
        migrations.RenameIndex(
            model_name='cgpahistory',
            new_name='cgpa_histor_action_41fe62_idx',
            old_name='cgpa_history_action_idx',
        ),
        migrations.RenameIndex(
            model_name='gradecomponent',
            new_name='grade_compo_subject_2d9343_idx',
            old_name='grade_compo_subject_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='subjectrecord',
            new_name='subject_rec_subject_5c997f_idx',
            old_name='cgpa_subject_code_idx',
        ),
        migrations.AlterField(
            model_name='academicprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semesterrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semesterrecord',
            name='semester_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectrecord',
            name='grade',
            field=models.CharField(choices=[('O', 'Outstanding (10)'), ('A+', 'Excellent (9)'), ('A', 'Very Good (8)'), ('B+', 'Good (7)'), ('B', 'Above Average (6)'), ('C', 'Average (5)'), ('P', 'Pass (4)'), ('F', 'Fail (0)')], default='O', max_length=2),
        ),
        migrations.AlterField(
            model_name='subjectrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjectrecord',
            name='subject_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='subjectrecord',
            name='subject_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='academicprofile',
            index=models.Index(fields=['-updated_at'], name='academic_pr_updated_7b13e3_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterrecord',
            index=models.Index(fields=['profile', 'semester'], name='semester_re_profile_45802a_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterrecord',
            index=models.Index(fields=['-sgpa'], name='semester_re_sgpa_e431d1_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectrecord',
            index=models.Index(fields=['semester_record'], name='subject_rec_semeste_69641c_idx'),
        ),
        migrations.AddField(
            model_name='academictarget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='academictarget',
            index=models.Index(fields=['user', '-created_at'], name='academic_ta_user_id_65d2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='academictarget',
            index=models.Index(fields=['user', 'is_achieved'], name='academic_ta_user_id_b2821c_idx'),
        ),
    ]
