# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notecomment_noteshare_notereport'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_branch_956621_idx',
            old_name='note_branch_sem_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_subject_461dd5_idx',
            old_name='note_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_status_400868_idx',
            old_name='note_status_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_created_f9cdd1_idx',
            old_name='notes_note_created_634102_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_downloa_bd34d2_idx',
            old_name='notes_note_downloa_309fe1_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='notes_upvotes_93e82d_idx',
            old_name='notes_note_upvotes_88f8ce_idx',
        ),
        migrations.RenameIndex(
            model_name='notecomment',
            new_name='note_commen_note_id_36c721_idx',
            old_name='note_cmt_note_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notecomment',
            new_name='note_commen_user_id_322f79_idx',
            old_name='note_cmt_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notereport',
            new_name='note_report_status_5abd84_idx',
            old_name='note_report_status_idx',
        ),
        migrations.RenameIndex(
            model_name='noteshare',
            new_name='note_shares_note_id_2341c9_idx',
            old_name='note_share_note_created_idx',
        ),
        migrations.RenameIndex(
            model_name='noteshare',
            new_name='note_shares_shared__b2fd43_idx',
            old_name='note_share_with_created_idx',
        ),
        migrations.RenameIndex(
            model_name='noteshare',
            new_name='note_shares_share_l_080560_idx',
            old_name='note_share_link_idx',
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notebookmark',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notevote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
