# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_community_roadmaps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['-is_featured', '-enrolled_count', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='roadmap',
            new_name='roadmaps_status_8933e3_idx',
            old_name='rm_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='roadmap',
            new_name='roadmaps_created_39b8a1_idx',
            old_name='rm_creator_status_idx',
        ),
        migrations.RenameIndex(
            model_name='roadmap',
            new_name='roadmaps_like_co_fc30dc_idx',
            old_name='rm_likes_idx',
        ),
        migrations.RenameIndex(
            model_name='roadmapcomment',
            new_name='roadmap_com_roadmap_07db2e_idx',
            old_name='rm_comment_roadmap_idx',
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='color',
            field=models.CharField(default='#6366F1', max_length=7),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='estimated_weeks',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='skills_covered',
            field=models.TextField(blank=True, default='', help_text='Comma-separated skills'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs Changes'), ('archived', 'Archived')], default='draft', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='roadmapmilestone',
            unique_together={('roadmap', 'order')},
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['category', 'status', 'is_active'], name='roadmaps_categor_446ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['is_active', '-enrolled_count'], name='roadmaps_is_acti_6440f6_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['slug'], name='roadmaps_slug_12ac74_idx'),
        ),
        migrations.AddIndex(
            model_name='studentroadmapprogress',
            index=models.Index(fields=['student', 'status'], name='student_roa_student_e32ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentroadmapprogress',
            index=models.Index(fields=['roadmap', 'status'], name='student_roa_roadmap_086cfb_idx'),
        ),
    ]
