# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='template_html',
            field=models.TextField(help_text='HTML/CSS template with Jinja-style placeholders'),
        ),
        migrations.AddIndex(
            model_name='resumeprofile',
            index=models.Index(fields=['student', '-updated_at'], name='resume_prof_student_a66c65_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeprofile',
            index=models.Index(fields=['student', 'is_primary'], name='resume_prof_student_644d08_idx'),
        ),
    ]
