# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_v2'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='newsannouncement',
            new_name='news_cat_active_idx',
            old_name='news_category_active_idx',
        ),
        migrations.AlterField(
            model_name='newsannouncement',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='newsannouncement',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=500),
        ),
    ]
