# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=500),
        ),
    ]
