# Generated by Django 4.2.13 on 2026-05-28 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('subject_code', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.PositiveSmallIntegerField()),
                ('section', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('period', models.CharField(blank=True, default='', max_length=20)),
                ('topic_covered', models.CharField(blank=True, default='', max_length=255)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_sessions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='faculty.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_records',
            },
        ),
        migrations.CreateModel(
            name='GradeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('subject_code', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.PositiveSmallIntegerField()),
                ('section', models.CharField(max_length=10)),
                ('exam_type', models.CharField(choices=[('internal_1', 'Internal 1'), ('internal_2', 'Internal 2'), ('internal_3', 'Internal 3'), ('mid_term', 'Mid Term'), ('end_term', 'End Term'), ('assignment', 'Assignment'), ('lab', 'Lab'), ('project', 'Project'), ('quiz', 'Quiz'), ('viva', 'Viva')], max_length=15)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grade_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['faculty', '-created_at'], name='grade_entri_faculty_d53ad2_idx'), models.Index(fields=['student', 'subject', 'semester'], name='grade_entri_student_9db38b_idx'), models.Index(fields=['branch', 'semester', 'section', 'subject'], name='grade_entri_branch_beddcf_idx')],
                'unique_together': {('student', 'subject', 'semester', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='FacultyResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('resource_type', models.CharField(choices=[('notes', 'Lecture Notes'), ('ppt', 'Presentation'), ('pdf', 'PDF Document'), ('recording', 'Recording'), ('syllabus', 'Syllabus'), ('question_paper', 'Question Paper'), ('other', 'Other')], default='notes', max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, default='', max_length=10)),
                ('file', models.FileField(upload_to='faculty_resources/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty_resources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['faculty', '-created_at'], name='faculty_res_faculty_76df12_idx'), models.Index(fields=['subject', 'branch', 'semester'], name='faculty_res_subject_88674e_idx'), models.Index(fields=['resource_type'], name='faculty_res_resourc_98c092_idx')],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('hod', 'Head of Department'), ('dean', 'Dean'), ('lecturer', 'Lecturer'), ('visiting', 'Visiting Faculty')], default='assistant_professor', max_length=30)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('specialization', models.CharField(blank=True, default='', max_length=255)),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('subjects', models.JSONField(blank=True, default=list, help_text='List of subjects taught')),
                ('sections_assigned', models.JSONField(blank=True, default=list, help_text='Assigned sections')),
                ('branches_assigned', models.JSONField(blank=True, default=list, help_text='Assigned branches')),
                ('semesters_assigned', models.JSONField(blank=True, default=list, help_text='Assigned semesters')),
                ('is_placement_coordinator', models.BooleanField(default=False)),
                ('is_class_advisor', models.BooleanField(default=False)),
                ('is_exam_coordinator', models.BooleanField(default=False)),
                ('can_verify_notes', models.BooleanField(default=True)),
                ('can_moderate_groups', models.BooleanField(default=True)),
                ('office_location', models.CharField(blank=True, default='', max_length=100)),
                ('office_hours', models.CharField(blank=True, default='', max_length=255)),
                ('phone_extension', models.CharField(blank=True, default='', max_length=20)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_assignments_created', models.PositiveIntegerField(default=0)),
                ('total_classes_taken', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty_profiles',
                'indexes': [models.Index(fields=['department'], name='faculty_pro_departm_a35540_idx'), models.Index(fields=['designation'], name='faculty_pro_designa_90b3ad_idx'), models.Index(fields=['is_active'], name='faculty_pro_is_acti_5f6a33_idx'), models.Index(fields=['user'], name='faculty_pro_user_id_39b84b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FacultyAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('target_branch', models.CharField(blank=True, default='', max_length=100)),
                ('target_semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_section', models.CharField(blank=True, default='', max_length=10)),
                ('target_subject', models.CharField(blank=True, default='', max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='faculty_announcements/')),
                ('attachment_name', models.CharField(blank=True, default='', max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty_announcements',
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['faculty', '-created_at'], name='faculty_ann_faculty_393ac0_idx'), models.Index(fields=['target_branch', 'target_semester', 'target_section'], name='faculty_ann_target__4084cf_idx'), models.Index(fields=['is_published', '-created_at'], name='faculty_ann_is_publ_141320_idx'), models.Index(fields=['priority'], name='faculty_ann_priorit_cfbc4c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['faculty', '-date'], name='attendance__faculty_3008b0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['branch', 'semester', 'section', '-date'], name='attendance__branch_2de14b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['subject', '-date'], name='attendance__subject_6ee6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'status'], name='attendance__session_523367_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'status'], name='attendance__student_cdd655_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
    ]
