# Generated by Django 4.2.13 on 2026-05-27 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0003_chat_tasks_resources_polls_timer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='group_chat__group_i_0dff54_idx',
            old_name='group_chat__group_i_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='group_chat__group_i_0ea75d_idx',
            old_name='group_chat__group_p_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='group_chat__sender__e9677e_idx',
            old_name='group_chat__sender_idx',
        ),
        migrations.RenameIndex(
            model_name='groupinvitation',
            new_name='group_invit_group_i_66b8d5_idx',
            old_name='study_group_inv_group_status_idx',
        ),
        migrations.RenameIndex(
            model_name='groupinvitation',
            new_name='group_invit_invited_45b8f6_idx',
            old_name='study_group_inv_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='groupinvitation',
            new_name='group_invit_token_58add1_idx',
            old_name='study_group_inv_token_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmeeting',
            new_name='group_meeti_group_i_fd65df_idx',
            old_name='study_group_meeting_status_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmeeting',
            new_name='group_meeti_group_i_25d893_idx',
            old_name='study_group_meeting_start_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_group_i_740f30_idx',
            old_name='study_group_member_group_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='group_membe_user_id_72052f_idx',
            old_name='study_group_member_user_idx',
        ),
        migrations.RenameIndex(
            model_name='grouppost',
            new_name='group_posts_group_i_32ff5b_idx',
            old_name='study_group_post_group_created_idx',
        ),
        migrations.RenameIndex(
            model_name='grouppost',
            new_name='group_posts_group_i_ffcc2e_idx',
            old_name='study_group_post_type_idx',
        ),
        migrations.RenameIndex(
            model_name='grouptask',
            new_name='group_tasks_group_i_aaad10_idx',
            old_name='group_tasks_grp_status_idx',
        ),
        migrations.RenameIndex(
            model_name='grouptask',
            new_name='group_tasks_assigne_cc108a_idx',
            old_name='group_tasks_assign_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroup',
            new_name='study_group_visibil_fb4a7c_idx',
            old_name='study_groups_vis_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroup',
            new_name='study_group_branch_795440_idx',
            old_name='study_groups_branch_sem_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroup',
            new_name='study_group_last_ac_b4ec65_idx',
            old_name='study_groups_activity_idx',
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='grouppoll',
            index=models.Index(fields=['group', 'is_active'], name='group_polls_group_i_b7c91c_idx'),
        ),
        migrations.AddIndex(
            model_name='grouptask',
            index=models.Index(fields=['group', 'position'], name='group_tasks_group_i_5fc1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedresource',
            index=models.Index(fields=['group', '-created_at'], name='group_share_group_i_64cca0_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedresource',
            index=models.Index(fields=['group', 'resource_type'], name='group_share_group_i_693d01_idx'),
        ),
        migrations.AddIndex(
            model_name='studytimer',
            index=models.Index(fields=['group', 'status'], name='group_study_group_i_6ef6d5_idx'),
        ),
    ]
