from django.urls import path
from .views import (
    QuestionListView,
    QuestionDetailView,
    QuestionTagsView,
    QuestionCompaniesView,
    QuestionLeaderboardView,
    MyCodingStatsView,
    QuestionEditorialView,
    QuestionCreateView,
    QuestionManageView,
    SaveQuestionView,
    UnsaveQuestionView,
    SavedQuestionsListView,
    SubmissionHistoryView,
    DraftView,
    DiscussionListCreateView,
    ContestListView,
    ContestDetailView,
    ContestRegisterView,
    ContestLeaderboardView,
    ContestMySubmissionsView,
    ContestSubmitView,
    ContestAdminCreateView,
    ContestAdminManageView,
)

urlpatterns = [
    path("", QuestionListView.as_view(), name="question-list"),
    path("tags", QuestionTagsView.as_view(), name="question-tags"),
    path("companies", QuestionCompaniesView.as_view(), name="question-companies"),
    path("leaderboard", QuestionLeaderboardView.as_view(), name="question-leaderboard"),
    path("my-stats", MyCodingStatsView.as_view(), name="question-my-stats"),
    path("create", QuestionCreateView.as_view(), name="question-create"),
    path("save", SaveQuestionView.as_view(), name="question-save"),
    path("saved", SavedQuestionsListView.as_view(), name="question-saved-list"),
    path("contests", ContestListView.as_view(), name="contest-list"),
    path("contests/create", ContestAdminCreateView.as_view(), name="contest-create"),
    path("<uuid:pk>", QuestionDetailView.as_view(), name="question-detail"),
    path("<uuid:pk>/editorial", QuestionEditorialView.as_view(), name="question-editorial"),
    path("<uuid:pk>/manage", QuestionManageView.as_view(), name="question-manage"),
    path("<uuid:pk>/unsave", UnsaveQuestionView.as_view(), name="question-unsave"),
    path("<uuid:pk>/submissions", SubmissionHistoryView.as_view(), name="question-submissions"),
    path("<uuid:pk>/draft", DraftView.as_view(), name="question-draft"),
    path("<uuid:pk>/discussions", DiscussionListCreateView.as_view(), name="question-discussions"),
    path("contests/<uuid:pk>", ContestDetailView.as_view(), name="contest-detail"),
    path("contests/<uuid:pk>/manage", ContestAdminManageView.as_view(), name="contest-manage"),
    path("contests/<uuid:pk>/register", ContestRegisterView.as_view(), name="contest-register"),
    path("contests/<uuid:pk>/leaderboard", ContestLeaderboardView.as_view(), name="contest-leaderboard"),
    path("contests/<uuid:pk>/submissions", ContestMySubmissionsView.as_view(), name="contest-submissions"),
    path("contests/<uuid:pk>/submit", ContestSubmitView.as_view(), name="contest-submit"),
]
